name: flutterfy
description: A tool to automatically manage version updates in pubspec.yaml.
version: 1.0.1+1727741864
repository: https://github.com/neryad/flutterfy

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
executables:
  flutterfy: flutterfy.dart
