name: flutterfy
description: A tool to automatically manage version updates in pubspec.yaml.
version: 1.0.0+1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
executables:
  pubspec_version_manager: lib/flutterfy.dart
